name: PR checks
'on':
  pull_request:
    branches:
      - master
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "VITE_CONTACT_SERVICE_KEY=${{ secrets.VITE_CONTACT_SERVICE_KEY }}" >> $GITHUB_ENV
          echo "VITE_CONTACT_TEMPLATE_KEY=${{ secrets.VITE_CONTACT_TEMPLATE_KEY }}" >> $GITHUB_ENV
          echo "VITE_CONTACT_SECRET_KEY=${{ secrets.VITE_CONTACT_SECRET_KEY }}" >> $GITHUB_ENV

      - run: npm ci
      - run: npm run lint
      - run: npm run test
